version: '3'
services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
      - "5000:5000"
    volumes:
      - ./jupyter:/tf/jupyter
  api:
    build: tensorflow/
    volumes:
      - ./jupyter:/tf
  web:
    build: dashboard/
    depends_on: 
      - api
    ports:
      - "80:80"
