version: '3'
services:
  jupyter:
    build: jupyter/
    ports:
      - "8888:8888"
      - "5000:5000"
    volumes:
      - ./jupyter/volume:/tf/jupyter
  api:
    build: tensorflow/
    volumes:
      - ./jupyter/volume:/tf
      - ./tensorflow:/app
  web:
    build: dashboard/
    volumes:
      - ./dashboard/public:/usr/share/nginx/html
    depends_on:
      - api
    ports:
      - "80:80"
