FROM tensorflow/tensorflow:latest-py3-jupyter
LABEL maintainer="Oscar Ablinger (dev.ablinger@gmail.com)"

RUN pip install imageio scikit-image keras Flask pandas seaborn

RUN jupyter notebook --generate-config
RUN echo "c.NotebookApp.password='sha1:d1763fe2e655:0b9e8421edd9744441ed4f6c90daa6fae9d83b81'" >> /root/.jupyter/jupyter_notebook_config.py

ENTRYPOINT jupyter notebook --notebook-dir=/tf --ip 0.0.0.0  --no-browser --allow-root
